# -*- coding: utf-8 -*-
"""Pregunta 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFu2njU52aXXr1zDrzoqqF6pTBrWFH7G
"""

import pandas as pd
import missingno as msno
from collections import Counter
import re

from google.colab import drive
drive.mount('/content/drive')

df1 = pd.read_csv('/content/drive/MyDrive/DD360/places_details.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DD360/places_reviews.csv')

pd.set_option('display.max_columns', None)

df1.head()

df1.tail()

df1.info()

df1.describe()

msno.bar(df1)

df2.head()

df2.tail()

df2.info()

df2.describe()

msno.bar(df2)

# Concatenar todos los textos de las reseñas
all_reviews_text = ' '.join(df2['text'].dropna())

# Eliminar caracteres especiales y convertir a minúsculas
all_reviews_text = re.sub(r'[^a-zA-Z0-9áéíóúñüÁÉÍÓÚÑÜ\s]', '', all_reviews_text).lower()

# Dividir el texto en palabras individuales
words = all_reviews_text.split()

# Contar la frecuencia de cada palabra
word_counts = Counter(words)

# Obtener las 109 palabras más comunes
top_words = word_counts.most_common(100)

# Imprimir las palabras más comunes
for word, count in top_words:
    print(f'{word}: {count}')